# Generated by Django 2.2.7 on 2019-11-24 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evalhubapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evalhubapp.DaycareUser')),
                ('assigner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evalhubapp.Evaluator')),
            ],
        ),
    ]
