# Generated by Django 2.2.7 on 2019-11-25 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evalhubapp', '0002_surveyassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyassignment',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evalhubapp.DaycareUser'),
        ),
        migrations.AlterField(
            model_name='surveyassignment',
            name='assigner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evalhubapp.Evaluator'),
        ),
    ]
