# Generated by Django 2.2.7 on 2019-11-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalhubapp', '0003_auto_20191124_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycareuser',
            name='invite_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='daycareuser',
            name='org_name',
            field=models.CharField(default='org', max_length=128),
            preserve_default=False,
        ),
    ]
