# Generated by Django 2.2.7 on 2019-11-25 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evalhubapp', '0004_auto_20191124_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
